### ISSUE TITLE
UNRELATED ~~[BUG][1.20.1][1.2.2d] Completely evaporates the tab content of some mods from existence.~~

### ISSUE THREAD

**Issue by VOLKOUL** [hypherionmc/MoreCreativeTabs#18]
You asked for help testing the mod, welp, here ya go:

**Describe the bug**
Simply installing this mod will completely remove the majority of items from some modded tabs. 

**To Reproduce**
  1. For example, download the Create Mod and some of it's addons.
  2. Download MoreCreativeTabs-combo-1.20-1.2.2d
  3. Go to the Create Mod tab.
  4. See how almost everything is missing.

**Expected behavior**
For items to not get yeeted out of existence.

**Versions (DO NOT USE "LATEST"! I STEAL YOUR KNEE CAPS!):**
- Minecraft Version: 1.20.1
- Modloader: NeoForge 
- Mod Loader Version: 47.1.100
- Mod Version: 1.2.2d

**Screenshots**
As you can see, the majority of items are missing. There are not even enough present to scroll through.
![Screenshot (941)](https://github.com/hypherionmc/MoreCreativeTabs/assets/97387920/0c5bd881-a306-43a5-a419-56f01a64bf85)

**Comment by hypherionmc** [comment]
Sigh... NeoForge... The one modloader this mod was never tested on....

I honestly don't know what to do with this mod anymore. It was so nice pre 1.20, and then mojang came and destroyed it all to the point where it's almost completely useless 😔

Seems like this will be one of those mods where we have to decide on only supporting a single mod loader, and making sure it works perfectly on that one, as forge/neoforge seem to be the biggest issues at this moment.


If anyone out there is willing to help to try and save this mod, please, please help me. 


Thanks for the feedback. Glad a release wasn't made after the PR was merged, as it would've only made things worse, instead of better

**Comment by VOLKOUL** [comment]
I suggest you focus on either NeoForge or Fabric. NeoForge seems to be the most promising one atm, as it derives from Forge, the one modloader that has the most modpacks made for it. (therefore there would be more people in need of a mod like yours) However, if you decide to focus on Fabric, we will hopefully be able to run it on NeoForge too by using Sinytra Connector.

**Comment by hypherionmc** [comment]
Yeah, while it's 70% easier to make this mod on fabric, NeoForge would be the bigger audience for it. More modpacks, more mods with complex tabs, overall, more in need of it, so I don't think fabric will be the target.

However, I've had some stuff in mind for ages to try and fix and "future proof" this mod, but lack of time for modding just haven't allowed me to explore it. As soon as I think I have time, a new Minecraft Version comes out, or another mod breaks.

I do not want to give up on this mod, as I personally use it in modpacks I play as well, and it's something the community wants, so it's worth trying to save it, even though the thought of abandoning it has been on my mind since the start of 1.20.

Hopefully someone more skilled than me can come across this issue and offer some guidance or help

**Comment by Wanderer70** [comment]
Yeah, I understand, modding is tough!
Don't overthink it, that would make it more complex.
Take ur time :D

**Comment by VOLKOUL** [comment]
**HEY HEY HEY HOLD UP WAAAIT!!!**
I may have screwed up a little. I wanted to make sure that it wasn't another mod conflict causing this and guess what... Thankfully, it appears that one of the Create addons is the culprit. Your mod seems to be completely fine. I will test a little bit more to see whether similar issues arise with More Creative Tabs, as there were only a few tabs affected.

**I AM SORRY!**

**Comment by VOLKOUL** [comment]
Yeah, I had updated some Create addons at the same time I downloaded this mod and thought that it was causing this. There are no such issues in MoreCreativeTabs, sorry!
