### ISSUE TITLE
[BUG][1.20.1][1.2.2d] Any page of the creative inventory other than the first one doesn't have the Search & Inventory tabs, nor proper separation.

### ISSUE THREAD

**Issue by VOLKOUL** [hypherionmc/MoreCreativeTabs#19]
**Describe the bug**
I don't know if that's intended behaviour, but the second, third, etc pages of the creative inventory do not have the Search and Inventory tabs. Their absence also means that there is no neat separation gap between modded tabs and these two (along with saved hotbars and Operator tab)

If there is a way to fix that via resourcepack/config sorry for reporting this.

**Versions (DO NOT USE "LATEST"! I STEAL YOUR KNEE CAPS!):**
- Minecraft Version: 1.20.1
- Modloader: NeoForge
- Mod Loader Version: 47.1.100
- Mod Version: 1.2.2d

**Screenshots**
Intended behaviour:
![Screenshot (939)](https://github.com/hypherionmc/MoreCreativeTabs/assets/97387920/b8b0f8a8-2f63-4ff7-8ef1-109389071b4f)

How it is:
![Screenshot (940)](https://github.com/hypherionmc/MoreCreativeTabs/assets/97387920/d4747c1d-34f0-459b-9575-675f60b5e78f)

**Comment by hypherionmc** [comment]
This is intentional. 

It was required for disabled tabs, and reordered tabs to be rendered properly. Keeping the vanilla behavior in place, meant tabs rendered over each other, or not at all, if you modified the positioning or even disabled any of the vanilla tabs.

Part of the many things 1.20+ broke for this mod
